site_name: Power PMAC Documentation
site_description: Global technical documentation for Power PMAC Multi-Axis Motion Controller
site_url: https://powerpmac.github.io/power-pmac-docs/

markdown_extensions:
  - md_in_html
  - attr_list
theme:
  name: material
  logo: assets/Cklogo.png
  # If you don't have a favicon yet, comment this line out
  # favicon: assets/omron-favicon.png

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.expand

    - search.highlight
    - search.suggest
    - search.share

    - content.code.copy
    - content.tabs.link

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/tasklist-persist.js


# Version selector (works with mike deployments)
extra:
  version:
    provider: mike
  # Optional: footer / social links
  
plugins:
  - search
  - tags
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      languages:
        - locale: en
          name: English
          default: true
          build: true

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# NAV (paths are relative to /docs)
nav:
  - Home: index.md
  - Application Notes:
      - Overview: application-notes/index.md
      - Motion & Kinematics: application-notes/motion-kinematics/index.md
      - EtherCAT & Networking: application-notes/ethercat-network/index.md
      - System Configuration: application-notes/system-configuration/index.md
      - Performance & Optimization: application-notes/performance-optimization/index.md
      - Migration & Legacy: application-notes/migration-legacy/index.md
      - Troubleshooting: application-notes/troubleshooting/index.md

  - Advanced Solutions:
      - Overview: advanced-solutions/index.md
      - Six Axis Robot Kinematics: advanced-solutions/six-axis-robot.md
      - 3D visuallisation with Power PMAC: advanced-solutions/pmac-visuallisation.md
      - Delta Robot Kinematics: advanced-solutions/delta-robot.md
      - Dual Link SCARA Robot Kinematics : advanced-solutions/dual-link-scara-robot.md
      - Hexapod Robot Kinematics: advanced-solutions/hexapod-robot.md

  - Learning:
      - Beginner: learning/beginner.md
      - Intermediate: learning/intermediate.md
      - Advanced: learning/advanced.md
  - Videos:
      - Video Tutorials: videos/index.md
  - Updates:
    - What's New: whats-new.md
    - Changelog: changelog.md
