theme:
  name: material
  logo: assets/omron-logo.png
  favicon: assets/omron-favicon.png   # optional
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - navigation.tracking

  palette:
    - scheme: default
      primary: red
      accent: red
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css
